### ISSUE TITLE
Is it OK with large bam files?

### ISSUE THREAD

**Issue by tao-bioinfo** [cmdcolin/sashimiplot#1]
The plugin requires bam file input. Is it OK with large bam files? For many RNA-seq mappings to a large (several GB) reference genome, the result bam file is usually several GB large

**Comment by cmdcolin** [comment]
Should be fine with pretty large BAM files. It is a little intensive, but not any more intensive than the default Alignments2 tracks, and maybe even less so because it doesn't have to draw as many things to the screen.

I was also thinking of allowing the input to be read from junctions.bed files for example, but I haven't gotten around to that yet.

**Comment by cmdcolin** [comment]
Also there might be an issue when viewing a very large area. It's possible that adding a "scale" limit to tell the user to zoom in to view more would be useful

**Comment by tao-bioinfo** [comment]
Thanks. I'll try it

**Comment by cmdcolin** [comment]
No worries! Here is a quick guide for installing the plugins that could help :) http://gmod.org/wiki/JBrowse_FAQ#How_do_I_install_a_plugin

**Comment by tao-bioinfo** [comment]
Well, I still hope `allowing the input to be read from junctions.bed`. File `junctions.bed` is much smaller than bam file. My disk space is poor...

**Comment by cmdcolin** [comment]
Agree!

**Comment by cmdcolin** [comment]
Should be fixed to allow junctions.bed now

Simply load the file with flatfile-to-json.pl, and then change the track "type" in trackList.json to SashimiPlot/View/Track/Sashimi

I added a sample configuration to README.md for this :)

**Comment by cmdcolin** [comment]
Note that interestingly, the "useXS" option still works with junctions.bed. Technically, the strand for the features in junctions.bed would be the same as if you were looking at the XS flag in the BAM file, so junctions.bed works very nicely now

**Comment by cmdcolin** [comment]
Given that, I'm tagging the first release of this plugin. Thanks for the suggestions @billzt :+1:
