### ISSUE TITLE
Will this plugin be adapted for the jbrowse 2 desktop?

### ISSUE THREAD

**Issue by mimi3421** [cmdcolin/sashimiplot#10]
I'm new to jbrowse and want to find a way to analyze alternate splicing in an easier way. (I'm fed up with the slow motion of IGV)
Will this plugin be adapted for the jbrowse 2 desktop?
Thanks.

**Comment by cmdcolin** [comment]
@mimi3421 hi there, thanks for the interest. We actually are trying to get a sashimi-plot style plugin added to jbrowse 2

We have a demo of it running here as a plugin https://github.com/cmdcolin/jbrowse-plugin-arc-renderer but we are thinking that it should actually get added to the core codebase (current PR to make it a core feature here https://github.com/GMOD/jbrowse-components/pull/2534)

**Comment by mimi3421** [comment]
Thank you so much for the great work! I'd like to have a try.
