### ISSUE TITLE
Grouped tracks

### ISSUE THREAD

**Issue by tao-bioinfo** [cmdcolin/sashimiplot#3]
Splice junctions for a certein gene locus might change among different experiment conditions, just like expression levels. For expression levels, we could use [multibigwig ](https://github.com/cmdcolin/multibigwig) plugin to group tracks. I would be very glad if sashimiplot tracks could also be grouped together. Otherwise we could be put multiple tracks in parallel. (which would be a mess if there are many experiment conditions)

**Comment by cmdcolin** [comment]
I would be interested in something like this too! If there are any ideas about what that might look like, then I'd be interested to hear them. Perhaps there might even be data preprocessing? The style->color and style->height callbacks are available for drawing too, so if somehow it is suitably preprocessed, then the drawing could be customized

**Comment by cmdcolin** [comment]
I made an update to multibigwig called MultiXYPlot. Perhaps this plugin can be extended to actually be sashimi plots (i.e. having both the coverage and junctions drawn on same track instead of just junctions)
