### ISSUE TITLE
Use tabix bed as datasource

### ISSUE THREAD

**Issue by keiranmraine** [cmdcolin/sashimiplot#4]
This is working on BAM but I'd like to pre-process into a format that will give the browser a speedup.  Ideally I'd like to use a tabix bed file as the input rather than convert to json as it would be a format that is useful for multiple tasks.

Would it be possible to slot this in as tabix is now supported more generally?

**Comment by cmdcolin** [comment]
Yep, BEDTabix actually works fine with sashimiplot. Just swap out storeClass to JBrowse/Store/SeqFeature/BEDTabix

tabix versions of the junctions.bed work for me for example

**Comment by cmdcolin** [comment]
Added a snippet to readme
